export const STATUS = {
	NULL: 0,
	LISTENING: 1,
	PLAYING: 2,
	WATCHING: 8,
	EDITING: 16,
	RESULT_SCREEN: 32,
};

export const STATUS_RAW = {
	CONNECTING: -3,
	UNKNOWN: -2,
	NOT_RUNNING: -1,
	MAIN_MENU: 0,
	EDITING_MAP: 1,
	PLAYING: 2,
	GAME_SHUTDOWN_ANIMATION: 3,
	SONG_SELECT_EDIT: 4,
	SONG_SELECT: 5,
	RESULTS_SCREEN: 7,
	GAME_STARTUP_ANIMATION: 10,
	MULTIPLAYER_ROOMS: 11,
	MULTIPLAYER_ROOM: 12,
	MULTIPLAYER_SONG_SELECT: 13,
	MULTIPLAYER_RESULTS_SCREEN: 14,
	OSU_DIRECT: 15,
	RANKING_TAG_COOP: 17,
	RANKING_TEAM: 18,
	PROCESSING_BEATMAPS: 19,
	TOURNEY: 22,
};

export const GRADES = {
	0: 'SSH',
	1: 'SH',
	2: 'SS',
	3: 'S',
	4: 'A',
	5: 'B',
	6: 'C',
	7: 'D',
	8: 'F',
	9: '',
};

export const SCORE_TYPE = {
	0: 'Local',
	1: 'Top',
	2: 'Selected mods',
	3: 'Friends',
	4: 'Country',
	10: 'Unknown',
};
